### PR TITLE
feat: add italy

### PR DESCRIPTION
**Pull request by augini**
This merge request includes the clink of wine from Italy. 
Oldik 🍷 !

### CODE REVIEW

**Comment by augini** [comment]
@rahmonov , is there any problem with the merge ?

**Comment by rahmonov** [comment]
@augini Sorry, absence of time is the biggest problem. Now there are some conflicts. Can you please fix them? Also can you show a gif demo? I am afraid that 3 frames may not be enough.

**Comment by augini** [comment]
>
ezgif com-gif-maker

@rahmonov , I have resolved the conflicts and here is the recorded GIF.
Yeah, I understand about the time, no worries.

**Comment by rahmonov** [comment]
@augini can you please add more frames? It looks weird with only 3 frames. The existing ones have 15-20 frames and thus look good.

**Pull request closed without merging**
