### PR TITLE
add version love glass

### PR DESCRIPTION
**Pull request by SanjarbekDev**
`python oldik.py --version=love
`

### CODE REVIEW

**Comment by rahmonov** [comment]
Hi @SanjarbekDev . Thanks for the PR. Can you please fix the conflicts and show a gif demo?

**Comment by SanjarbekDev** [comment]
Ok

**Comment by SanjarbekDev** [comment]
gif demo [here!](https://youtu.be/lrwD88aoccs)

**Review by rahmonov — APPROVED** [review]
Sweet! Thanks

**Pull request merged**
